name: CI

on:
  - push
  - workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check code for compiler errors
        run: cargo check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check code format
        run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint code
        run: cargo clippy -- -D warnings

  p1-output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: cargo build --bin two_sample
      - uses: GuillaumeFalourd/assert-command-line-output@v2.3
        with:
          command_line: ./target/debug/two_sample
          assert_file_path: sample-files/cats.out.correct
